# Service Configuration
server.port=8081
spring.application.name=account-service

# Database Configuration (MySQL/Oracle)
spring.datasource.url=jdbc:mysql://localhost:3306/pob_bank
spring.datasource.username=root
spring.datasource.password=your_strong_password
# This wipes the DB every time you start/stop the app
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# Performance Tuning for 1M+ Records
spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_inserts=true